// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

List<Receipt> fetchReceipts() =>
    RustLib.instance.api.crateApiSimpleFetchReceipts();

class Item {
  final String name;
  final double unitPrice;
  final double count;
  final double price;

  const Item({
    required this.name,
    required this.unitPrice,
    required this.count,
    required this.price,
  });

  @override
  int get hashCode =>
      name.hashCode ^ unitPrice.hashCode ^ count.hashCode ^ price.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Item &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          unitPrice == other.unitPrice &&
          count == other.count &&
          price == other.price;
}

class Receipt {
  final String? nip;
  final Store store;
  final List<Item> items;
  final double total;
  final DateTime date;

  const Receipt({
    this.nip,
    required this.store,
    required this.items,
    required this.total,
    required this.date,
  });

  @override
  int get hashCode =>
      nip.hashCode ^
      store.hashCode ^
      items.hashCode ^
      total.hashCode ^
      date.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Receipt &&
          runtimeType == other.runtimeType &&
          nip == other.nip &&
          store == other.store &&
          items == other.items &&
          total == other.total &&
          date == other.date;
}

@freezed
sealed class Store with _$Store {
  const Store._();

  const factory Store.biedronka() = Store_Biedronka;
  const factory Store.lidl() = Store_Lidl;
  const factory Store.other(String field0) = Store_Other;
}
